### ISSUE TITLE
Potential Reentrancy Risk Due to Non-Strict CEI Pattern Adherence

### ISSUE THREAD

**Issue by syed-ghufran-hassan** [PufferFinance/puffer-contracts#74]
https://github.com/PufferFinance/puffer-contracts/blob/master/l2-contracts/src/L2RewardManager.sol#L55L111

There is potential reentrancy in claim rewards function which can be mitigated by following CEI pattern.

The token transfer (XPUFETH.transfer) occurs after the state change 

```solidity
$.claimedRewards[claimOrders[i].intervalId][claimOrders[i].account] = true; 
```

Ideally, state changes should occur after external calls to avoid reentrancy risks.

**Comment by bxmmm1** [comment]
You are right, but we are dealing with ERC20 token that doesn't allow for reentrancy. Because of that, the CEI pattern doesn't need to be followed.
